"""add_github_access_token_to_users

Revision ID: 6020afc1e4a0
Revises: f087743c5b5e
Create Date: 2026-05-27 22:05:55.117606

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '6020afc1e4a0'
down_revision = 'f087743c5b5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_access_token')
    # ### end Alembic commands ###
