TOKEN_TYPE_BEARER = "bearer"
PASSWORD_HASH_SCHEME = "bcrypt"
PASSWORD_MIN_LENGTH = 8
API_KEY_PREFIX = "dp_"
API_KEY_LENGTH = 32
GITHUB_TOKEN_FIELD = "github_access_token"
JWT_SUBJECT_FIELD = "sub"
JWT_EXPIRY_FIELD = "exp"